"""ZeroTier cluster 자동 discovery — env 변경 없이 port probing.

각 노드가 어떤 서버를 돌리는지 자동 감지:
  8001 → μ vLLM   (/v1/models 응답 OK이면 μ)
  8002 → PRM      (/health 응답 OK이면 PRM)
  (한 노드에 둘 다 있으면 둘 다 등록)

사용:
    # 학습 PC에서
    docker exec pav-zerotier sh -c "apk add --no-cache python3 || true; python3 -" < scripts/cluster_discovery.py
    # 또는
    python3 scripts/cluster_discovery.py > nginx/inference-cluster.conf
    docker compose restart nginx-lb

자체 ZeroTier IP/subnet 자동 감지 → 그 subnet의 모든 IP 병렬 prob.
"""
from __future__ import annotations

import json
import subprocess
import sys
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor


PROBE_TIMEOUT = 2.0   # 각 IP prob HTTP timeout (초)


def get_self_subnet() -> tuple[str, str]:
    """ZeroTier 자기 IP 자동 감지. (self_ip, subnet_prefix) 반환.

    감지 순서:
      1. env SELF_IP 명시
      2. /proc/net/fib_trie 또는 ip 명령 (Linux 컨테이너)
      3. socket trick fallback
    """
    import os, socket
    # 1. 명시적 env
    if os.environ.get("SELF_IP"):
        ip = os.environ["SELF_IP"]
        return ip, ".".join(ip.split(".")[:3])

    # 2. ip 명령으로 ZeroTier 인터페이스 (보통 zt 또는 ztXXX) IP 찾기
    try:
        out = subprocess.check_output(["ip", "-4", "addr"], text=True, timeout=5)
        for line in out.splitlines():
            # "inet 10.12.197.216/24 ... scope global ztXXX"
            line = line.strip()
            if line.startswith("inet ") and ("zt" in line or "10." in line):
                parts = line.split()
                ip_cidr = parts[1]   # "10.12.197.216/24"
                ip = ip_cidr.split("/")[0]
                if ip.startswith("10.") or ip.startswith("172.16.") or ip.startswith("192.168."):
                    # ZeroTier 가상 IP일 가능성 (10.x가 흔함)
                    if "zt" in line:
                        return ip, ".".join(ip.split(".")[:3])
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        pass

    # 3. socket trick — 가짜 connect로 default route 인터페이스 IP 알아냄
    for guess in ["10.255.255.255", "10.0.0.1", "172.16.0.1"]:
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.settimeout(0.5)
            s.connect((guess, 1))
            ip = s.getsockname()[0]
            s.close()
            if ip.startswith("10.") and not ip.startswith("10.0.0."):
                return ip, ".".join(ip.split(".")[:3])
        except OSError:
            pass

    sys.stderr.write("self IP 자동 감지 실패 — env SELF_IP=10.x.x.x 명시 후 재실행.\n")
    sys.exit(1)


def probe(ip: str, port: int, path: str) -> bool:
    """주어진 IP:port/path에 GET. 200 응답이면 True."""
    try:
        req = urllib.request.Request(f"http://{ip}:{port}{path}")
        with urllib.request.urlopen(req, timeout=PROBE_TIMEOUT) as r:
            return r.status == 200
    except (urllib.error.URLError, urllib.error.HTTPError, ConnectionError, OSError):
        return False


def probe_node(ip: str) -> dict:
    """한 IP에 8001, 8002 prob. 결과 dict 반환."""
    return {
        "ip": ip,
        "mu": probe(ip, 8001, "/v1/models"),
        "prm": probe(ip, 8002, "/health"),
    }


def main():
    self_ip, prefix = get_self_subnet()
    sys.stderr.write(f"# self: {self_ip}  subnet: {prefix}.0/24\n")

    candidates = [f"{prefix}.{i}" for i in range(1, 255) if f"{prefix}.{i}" != self_ip]
    sys.stderr.write(f"# probing {len(candidates)} IPs (8001/μ, 8002/PRM)...\n")

    with ThreadPoolExecutor(max_workers=64) as ex:
        results = list(ex.map(probe_node, candidates))

    mu_ips = [r["ip"] for r in results if r["mu"]]
    prm_ips = [r["ip"] for r in results if r["prm"]]
    sys.stderr.write(f"# found  μ: {mu_ips}\n")
    sys.stderr.write(f"# found  PRM: {prm_ips}\n")

    # nginx config 생성 → stdout
    print("# Auto-generated by scripts/cluster_discovery.py")
    print(f"# self: {self_ip}  subnet: {prefix}.0/24")
    print()
    print("upstream mu_cluster {")
    print("    least_conn;")
    if not mu_ips:
        print("    server 127.0.0.1:8001 down;   # discovery 결과 없음 (placeholder)")
    for ip in mu_ips:
        print(f"    server {ip}:8001 max_fails=3 fail_timeout=30s;")
    print("}")
    print()
    print("upstream prm_cluster {")
    print("    least_conn;")
    if not prm_ips:
        print("    server 127.0.0.1:8002 down;   # discovery 결과 없음")
    for ip in prm_ips:
        print(f"    server {ip}:8002 max_fails=3 fail_timeout=30s;")
    print("}")
    print()
    print("server { listen 18001; location / { proxy_pass http://mu_cluster;")
    print("    proxy_read_timeout 600s; proxy_send_timeout 600s; proxy_connect_timeout 30s; proxy_buffering off; } }")
    print("server { listen 18002; location / { proxy_pass http://prm_cluster;")
    print("    proxy_read_timeout 300s; proxy_send_timeout 300s; proxy_connect_timeout 30s; proxy_buffering off; } }")


if __name__ == "__main__":
    main()
